# @axe-core/cli
name: axe
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  axe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on http://localhost:3000
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:3000 --exit
      

